# Generated by Django 4.2.30 on 2026-07-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='creaeted_at',
            new_name='created_at',
        ),
    ]
