# Generated by Django 4.2.30 on 2026-07-16 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, help_text='Comma-separated, e.g. S,M,L,XL or 6,7,8,9,10', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='size_type',
            field=models.CharField(choices=[('none', 'No Size (bags, equipment, etc.)'), ('clothing', 'Clothing (S/M/L/XL)'), ('shoe', 'Shoe Size (6-12)')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'unique_together': {('product', 'size')},
            },
        ),
    ]
